name: dallas-dev
recipe: lamp
config:
  php: '8.0'
  webroot: src
  via: apache

services:
  appserver:
    build_as_root:
      - apt-get update -y
      - apt-get install -y git unzip
    build:
      - composer install
  database:
    type: mysql:5.7
    portforward: true
    creds:
      user: lando
      password: lando
      database: mydatabase

proxy:
  appserver:
    - dallas-dev.lndo.site

tooling:
  composer:
    service: appserver
  php:
    service: appserver
  mysql:
    service: database
